### PR TITLE
support appending filename for formdata

### PR DESCRIPTION
**Pull request by ashercoren**
See: https://developer.mozilla.org/en-US/docs/Web/API/FormData/append#Syntax

### CODE REVIEW

**Comment by r0man** [comment]
Hi @ashercoren,
could you also provide an example how to use this?
A test would also be nice, if possible.
Roman

**Comment by ashercoren** [comment]
@r0man I will try writing a test. How do I run the tests?

**Comment by ashercoren** [comment]
@r0man I would like my pull request to be merged. Can you tell me how to run the tests for your library so I can write one for my pull request?

**Comment by r0man** [comment]
Hi Asher, sorry for the delay, I'm traveling at the moment. I think a "lein
cljsbuild test" should run the tests ...

**Comment by ashercoren** [comment]
@r0man I couldn't find a way to write a test, since the get methods of formData are not implemented in phantomJS. I did change my code a little so that it will be more understandable. 
I hope it is good enough for you to merge the pull request.

**Comment by r0man** [comment]
@ashercoren Sorry, still on the road. Would it make more sense to use a `:filename` key instead of the vector?

**Comment by ashercoren** [comment]
@r0man Do you mean something like this:
`{my-file: {:value value :filename filename}}`?
I think the vector options is better because it's closer to the formData syntax.

**Comment by r0man** [comment]
@ashercoren Ok, let's go with the vector. Can you resolve the conflicts, then I'll merge it,

**Comment by ashercoren** [comment]
@r0man rebased. Thanks!

**Comment by r0man** [comment]
Thanks, released as `0.1.37`.

**Comment by ashercoren** [comment]
Thank you! I hope you enjoyed your vacation.

**Comment by r0man** [comment]
I'm still enjoying it ... :)

**Pull request merged**
