### PR TITLE
upload/download progress reporting

### PR DESCRIPTION
**Pull request by aav**

### CODE REVIEW

**Comment by r0man** [comment]
Hey Alexey,
I'm on holiday until end of January. I'll take a look at this when I am
back.
Roman
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/r0man/cljs-http/pull/89
Commit Summary

   - upload/download progress reporting

File Changes

   - *M* README.md <https://github.com/r0man/cljs-http/pull/89/files#diff-0>
   (12)
   - *M* src/cljs_http/core.cljs
   <https://github.com/r0man/cljs-http/pull/89/files#diff-1> (12)

Patch Links:

   - https://github.com/r0man/cljs-http/pull/89.patch
   - https://github.com/r0man/cljs-http/pull/89.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/r0man/cljs-http/pull/89>.

**Comment by jwr** [comment]
I could make use of this. Any reason why this is not in, other than lack of time? Any blockers?

**Comment by r0man** [comment]
@aav and @jwr Sorry, I forgot about this. @aav If you still want this to be merged into cljs-http, could you also write a test for this?

**Comment by aav** [comment]
@r0man  yes. sure, i will take care of tests

**Pull request merged**
